### ISSUE TITLE
`setup.py test` failed in develop branch

### ISSUE THREAD

**Issue by ssmi1975** [openql-org/quantpy#29]
I have tried to run test in `develop` branch, but it failed with `TypeError: qapply() missing 1 required positional argument: 'circuit'`.

[environment]
MacOSX, 10.14.2 (Mojave)

[steps]
1. clone repository
2. create venv and enabled it `python3 -m venv _e; . _e/bin/activate`
3. install dependencies by pip `pip install -r requirements.txt`
4. execute setup.py `python setup.py test`

[expected]
test passed successfully

[actual]
test failed with the following errors.

```
$ python setup.py test
running test
running egg_info
writing quantpy.egg-info/PKG-INFO
writing dependency_links to quantpy.egg-info/dependency_links.txt
writing requirements to quantpy.egg-info/requires.txt
writing top-level names to quantpy.egg-info/top_level.txt
package init file 'quantpy/ising/__init__.py' not found (or not a regular file)
reading manifest file 'quantpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'quantpy/ising/__pycache__'
writing manifest file 'quantpy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    install_requires=_requirements(),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/susumu/study/openql/quantpy/_e/lib/python3.6/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/Users/susumu/study/openql/quantpy/_e/lib/python3.6/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/Users/susumu/study/openql/quantpy/_e/lib/python3.6/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/susumu/study/openql/quantpy/_e/lib/python3.6/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
TypeError: qapply() missing 1 required positional argument: 'circuit'
```

**Comment by openql-org** [comment]
I have been able to reproduce this issue. It was as you have pointed out.

**Comment by openql-org** [comment]
Further, thank you for your fixing. I merged your pull-request to the feature branch.
