### ISSUE TITLE
ibmq_executor doesn't work

### ISSUE THREAD

**Issue by ssmi1975** [openql-org/quantpy#36]
version  : 0.0.2.dev9

I have noticed I have broken the imbq_execute by the PR https://github.com/openql-org/quantpy/pull/33 . 

[Reproduction steps]
execute this code.

```
from sympy.physics.quantum.gate import H
from sympy.physics.quantum.qubit import Qubit
from quantpy.sympy.qapply import qapply
import sympy
from quantpy.sympy.executor.classical_simulation_executor import ClassicalSimulationExecutor
from quantpy.sympy.executor.sympy_executor import SymPyExecutor
from quantpy.sympy.executor.ibmq_executor import IBMQExecutor

c = H(2)*H(1)*H(0)*Qubit('000')
assert isinstance(c, sympy.mul.Mul)
for executor in (SymPyExecutor(), ClassicalSimulationExecutor(), IBMQExecutor()):
    result = qapply(c, executor=executor)
    print(result)
    print(result.__class__)
```

[Expected]
the script executed without any errors

[Actual]
It failed with the following error.
```
$ python t.py
/Users/susumu/study/openql/quantpy/_v/lib/python3.6/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
Traceback (most recent call last):
  File "t.py", line 11, in <module>
    for executor in (SymPyExecutor(), ClassicalSimulationExecutor(), IBMQExecutor()):
  File "/Users/susumu/study/openql/quantpy/quantpy/sympy/executor/ibmq_executor.py", line 34, in __init__
    quantum_program = qiskit.QuantumProgram()
AttributeError: module 'qiskit' has no attribute 'QuantumProgram'
```

**Comment by openql-org** [comment]
I confirm the script executed without any errors.
